# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "rabbit"
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  config.vm.provision "shell", path: "provision.sh"

end

